<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function form_examples_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['name']['#description'] = t('Enter your username, as assigned by IT.');
    $form['pincode'] = [
      '#type' => 'password',
      '#title' => t('PIN Code'),
      '#description' => t('Enter your super-secret PIN code.'),
      '#required' => TRUE,
    ];
    $form['#validate'][] = 'form_examples_check_pin';
    $form['#submit'][] = 'form_examples_log_logins';
  }
}


function form_examples_check_pin(array &$form, FormStateInterface $form_state) {
  $pin = $form_state->getValue('pincode');
  if (empty($pin) || $pin !== '1234') {
    $form_state->setErrorByName('pincode', t('Invalid PIN code.'));
  }
}

function form_examples_log_logins(array &$form, FormStateInterface $form_state) {
  \Drupal::messenger()->addWarning(t('Your login as been logged for future reference.'));
}


/**
 * Implements hook_mail().
 */
function form_examples_mail($key, &$message, $params) {
  if ($key === 'contact_form') {
    $message['subject'] = t('Message from the website contact form');
    $message['body'][] = t('The following message was entered on the website.');
    $message['body'][] = t('Name: @name', ['@name' => $params['name']]);
    $message['body'][] = t('Email: @email', ['@email' => $params['email']]);
    $message['body'][] = $params['message'];
  }
}
